(() => {
  "use strict";

  const API_BASE = (window.MESSAGEQUEUE_API_BASE || "/api").replace(/\/$/, "");
  const API_PREFIX = "/v1/messagequeues";
  const DEMO_CLUSTERS = [
    {
      metadata: { name: "orders-prod", namespace: "workspace-main", creationTimestamp: "2026-07-24T06:08:00Z" },
      spec: { engine: "kafka", kafka: { version: "3.9.0", replicas: 3 }, storage: { size: "64Gi", className: "premium-rwo" }, deletionPolicy: "Retain" },
      status: { phase: "Ready", ready: true, observedGeneration: 4, endpoint: "orders-prod-kafka-bootstrap.workspace-main.svc:9092", lastTransitionTime: "2026-07-24T06:14:18Z", conditions: [{ type: "Ready", status: "True", reason: "KafkaReady", message: "Kafka brokers are accepting connections." }, { type: "ObservabilityReady", status: "True", reason: "ScrapeConfigured", message: "Broker metrics and logs are available." }], events: [{ time: "12 min ago", message: "KafkaUser credentials reconciled." }, { time: "18 min ago", message: "All 3 brokers reported Ready." }] }
    },
    {
      metadata: { name: "events-dev", namespace: "workspace-main", creationTimestamp: "2026-07-28T03:52:00Z" },
      spec: { engine: "kafka", kafka: { version: "3.9.0", replicas: 1 }, storage: { size: "20Gi", className: "standard" }, deletionPolicy: "Retain" },
      status: { phase: "Provisioning", ready: false, observedGeneration: 1, endpoint: "Pending", lastTransitionTime: "2026-07-28T03:52:00Z", conditions: [{ type: "Ready", status: "False", reason: "WaitingForBrokers", message: "Waiting for the Kafka broker pod to become Ready." }], events: [{ time: "2 min ago", message: "MessageQueue accepted by the controller." }, { time: "1 min ago", message: "Kafka resource created through Strimzi." }] }
    }
  ];

  const state = { clusters: [], selected: null, tab: "overview", loading: true, apiState: "loading", apiMessage: "", search: "", observability: {}, createSubmitting: false };
  const $ = (selector) => document.querySelector(selector);
  const escapeHtml = (value) => String(value ?? "").replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[character]));
  const formatTime = (value) => { if (!value) return "Unknown"; const date = new Date(value); return Number.isNaN(date.getTime()) ? String(value) : new Intl.DateTimeFormat("en", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }).format(date); };
  const formatStatus = (phase) => { const value = String(phase || "Unknown").toLowerCase(); const map = { ready: ["Ready", "ready"], provisioning: ["Provisioning", "provisioning"], creating: ["Provisioning", "provisioning"], updating: ["Updating", "updating"], degraded: ["Degraded", "degraded"], failed: ["Failed", "failed"], suspended: ["Suspended", "suspended"], deleting: ["Deleting", "deleting"] }; return map[value] || [phase || "Unknown", "degraded"]; };
  const parseSizeGi = (value) => { const match = String(value ?? "").match(/([0-9]+(?:\.[0-9]+)?)/); return match ? Number(match[1]) : 20; };
  const normalize = (raw) => { const metadata = raw?.metadata || {}; const spec = raw?.spec || {}; const kafka = spec.kafka || {}; const storage = spec.storage || {}; const status = raw?.status || {}; const conditions = Array.isArray(status.conditions) ? status.conditions : []; const phase = status.phase || (conditions.find((condition) => condition.type === "Ready" && condition.status === "True") ? "Ready" : "Provisioning"); const firstEndpoint = status.endpoints?.[0]; const endpoint = status.endpoint || status.bootstrapEndpoint || (typeof firstEndpoint === "string" ? firstEndpoint : firstEndpoint ? `${firstEndpoint.host}:${firstEndpoint.port}` : "Pending"); return { raw, metadata, spec, kafka, storage, status, conditions, name: metadata.name || raw.name || "unnamed-cluster", namespace: metadata.namespace || raw.namespace || "workspace", brokers: Number(kafka.brokers || kafka.replicas || spec.replicas || spec.brokers || status.topology?.brokers || 1), storageGi: parseSizeGi(kafka.storageGi || storage.size || spec.storageGi || 20), version: kafka.version || status.version || spec.version || "3.9.0", storageClass: kafka.storageClass || storage.storageClass || storage.className || storage.class || "default", deletionPolicy: spec.deletionPolicy || storage.deletionPolicy || "unspecified", phase, endpoint, lastTransitionTime: status.lastTransitionTime || status.conditions?.[0]?.lastTransitionTime || metadata.creationTimestamp || raw.creationTimestamp, events: Array.isArray(status.events) ? status.events : [] }; };
  const normalizedClusters = () => state.clusters.map(normalize);
  const selectedCluster = () => normalizedClusters().find((cluster) => cluster.name === state.selected) || normalizedClusters()[0] || null;

  async function request(path, options = {}) {
    const response = await fetch(`${API_BASE}${path}`, { headers: { "Content-Type": "application/json", Accept: "application/json" }, credentials: "include", ...options });
    if (response.status === 403) { const error = new Error("Permission denied"); error.code = 403; throw error; }
    if (!response.ok) { const body = await response.text(); const error = new Error(body || `Request failed (${response.status})`); error.code = response.status; throw error; }
    if (response.status === 204) return null;
    return response.json();
  }

  function setApiState(apiState, message = "") { state.apiState = apiState; state.apiMessage = message; const indicator = $("#api-indicator"); indicator.dataset.state = apiState; $("#api-indicator-label").textContent = ({ loading: "Connecting", ready: "API connected", degraded: "API degraded", forbidden: "Access denied" })[apiState] || apiState; }
  function renderNotice() { const region = $("#notice-region"); if (state.apiState === "degraded") region.innerHTML = `<div class="notice" data-tone="warning"><span class="notice-icon" aria-hidden="true">!</span><div class="notice-copy"><strong>Management API unavailable</strong><p>${escapeHtml(state.apiMessage || "Showing clearly labelled demo data. Changes require an available API.")}</p></div><button class="icon-button notice-close" type="button" aria-label="关闭提示" data-action="dismiss-notice">×</button></div>`; else if (state.apiState === "forbidden") region.innerHTML = `<div class="notice" data-tone="error"><span class="notice-icon" aria-hidden="true">!</span><div class="notice-copy"><strong>Permission denied</strong><p>Your session cannot read MessageQueue resources in this workspace.</p></div></div>`; else region.innerHTML = ""; }
  function renderStats(clusters) { const ready = clusters.filter((cluster) => formatStatus(cluster.phase)[1] === "ready").length; const attention = clusters.length - ready; $("#stat-total").textContent = state.loading ? "--" : clusters.length; $("#stat-ready").textContent = state.loading ? "--" : ready; $("#stat-attention").textContent = state.loading ? "--" : attention; $("#stat-total-meta").textContent = state.apiState === "degraded" ? "Demo data · API unavailable" : "Observed in this workspace"; $("#nav-count").textContent = state.loading ? "--" : clusters.length; $("#workspace-name").textContent = clusters[0]?.namespace || "workspace"; }
  function filteredClusters() { const query = state.search.trim().toLowerCase(); return normalizedClusters().filter((cluster) => !query || `${cluster.name} ${cluster.namespace} ${cluster.version}`.toLowerCase().includes(query)); }
  function renderClusterList() { const list = $("#cluster-list"); list.setAttribute("aria-busy", state.loading ? "true" : "false"); if (state.loading) { list.innerHTML = `<div class="loading-state"><span>Loading observed clusters…</span><span class="loading-bar" aria-hidden="true"></span></div>`; return; } const clusters = filteredClusters(); $("#list-subtitle").textContent = state.apiState === "degraded" ? `${clusters.length} demo resources · read only` : `${clusters.length} resource${clusters.length === 1 ? "" : "s"} in your workspace`; if (!clusters.length) { list.innerHTML = `<div class="empty-state"><strong>${state.search ? "No matching clusters" : "No Kafka clusters yet"}</strong><p>${state.search ? "Try a different name or clear the search." : "Create a development cluster to start producing messages."}</p>${state.search ? "" : `<button class="button button-primary" type="button" data-action="open-create">+ Create cluster</button>`}</div>`; return; } list.innerHTML = clusters.map((cluster) => { const [label, statusClass] = formatStatus(cluster.phase); return `<button type="button" class="cluster-row ${cluster.name === state.selected ? "is-selected" : ""}" data-cluster="${escapeHtml(cluster.name)}" aria-pressed="${cluster.name === state.selected}"><span><span class="cluster-name">${escapeHtml(cluster.name)}</span><span class="cluster-meta"><code>${escapeHtml(cluster.namespace)}</code> · Kafka ${escapeHtml(cluster.version)}</span></span><span class="cluster-status"><span class="status-badge status-${statusClass}">${escapeHtml(label)}</span></span><span class="cluster-topology"><strong>${cluster.brokers} broker${cluster.brokers === 1 ? "" : "s"}</strong><span>${cluster.storageGi} Gi / broker</span></span><span class="cluster-action" aria-hidden="true">›</span></button>`; }).join(""); }
  function renderDetail() { const panel = $("#detail-content"); const cluster = selectedCluster(); if (!cluster) { panel.innerHTML = `<div class="empty-state"><strong>Select a cluster</strong><p>Choose a resource from the list to inspect its observed status.</p></div>`; return; } const [label, statusClass] = formatStatus(cluster.phase); const tab = state.tab; panel.innerHTML = `<div class="detail-header"><div class="detail-title"><h2 id="detail-title">${escapeHtml(cluster.name)}</h2><p><code>${escapeHtml(cluster.namespace)}</code> · last transition ${escapeHtml(formatTime(cluster.lastTransitionTime))}</p></div><div class="detail-actions"><span class="status-badge status-${statusClass}">${escapeHtml(label)}</span><button class="button button-secondary" type="button" data-action="refresh-detail">↻ Refresh</button></div></div><div class="detail-tabs" role="tablist" aria-label="Cluster detail tabs">${[ ["overview", "Overview"], ["connections", "Connections"], ["logs", "Logs"], ["metrics", "Metrics"] ].map(([id, title]) => `<button class="tab-button ${tab === id ? "is-active" : ""}" type="button" role="tab" aria-selected="${tab === id}" data-tab="${id}">${title}${id === "logs" && !state.observability.logs ? "" : ""}</button>`).join("")}</div><div class="detail-body">${tab === "overview" ? overviewHtml(cluster) : tab === "connections" ? connectionsHtml(cluster) : tab === "logs" ? logsHtml(cluster) : metricsHtml(cluster)}</div>`; if (tab === "logs" && state.observability.logs?.name === cluster.name && state.observability.logs.data) { const viewer = $("#log-viewer"); if (viewer) viewer.textContent = state.observability.logs.data; } }
  function overviewHtml(cluster) { const conditions = cluster.conditions.length ? cluster.conditions : [{ type: "Ready", status: "Unknown", reason: "NoCondition", message: "The controller has not reported a condition yet." }]; const events = cluster.events.length ? cluster.events : [{ time: "—", message: "No recent events reported." }]; const deletionPolicy = cluster.deletionPolicy === "delete" || cluster.deletionPolicy === "Delete" ? "Delete with cluster" : cluster.deletionPolicy === "retain" || cluster.deletionPolicy === "Retain" ? "Retain data" : "Controller default"; return `<section class="detail-section"><div class="section-heading"><h3>Observed state</h3><span>generation ${escapeHtml(cluster.status.observedGeneration || "—")}</span></div><dl class="info-grid"><div class="info-item"><dt>Engine</dt><dd>Apache Kafka</dd></div><div class="info-item"><dt>Kafka version</dt><dd>${escapeHtml(cluster.version)}</dd></div><div class="info-item"><dt>Topology</dt><dd>${cluster.brokers} broker${cluster.brokers === 1 ? "" : "s"}</dd></div><div class="info-item"><dt>Storage</dt><dd>${cluster.storageGi} Gi / broker</dd></div><div class="info-item"><dt>Bootstrap endpoint</dt><dd><code>${escapeHtml(cluster.endpoint)}</code></dd></div><div class="info-item"><dt>Deletion policy</dt><dd>${deletionPolicy}</dd></div></dl></section><section class="detail-section"><div class="section-heading"><h3>Conditions</h3><span>controller reported</span></div><div class="condition-list">${conditions.map((condition) => `<div class="condition-row"><strong>${escapeHtml(condition.type || "Condition")} · ${escapeHtml(condition.status || "Unknown")}</strong><span>${escapeHtml(condition.message || condition.reason || "No message")}</span></div>`).join("")}</div></section><section class="detail-section"><div class="section-heading"><h3>Recent events</h3><span>latest first</span></div><div class="event-list">${events.map((event) => `<div class="event-row"><time>${escapeHtml(event.time || formatTime(event.lastTimestamp))}</time><p>${escapeHtml(event.message || event.reason || "Controller event")}</p></div>`).join("")}</div></section>`; }
  function connectionsHtml(cluster) { return `<section class="detail-section"><div class="section-heading"><h3>Client connection</h3><span>credentials stay server-side</span></div><div class="connection-block"><div class="copy-row"><code>${escapeHtml(cluster.endpoint)}</code><button type="button" data-copy="${escapeHtml(cluster.endpoint)}">Copy</button></div><div class="notice" data-tone="warning"><span class="notice-icon" aria-hidden="true">i</span><div class="notice-copy"><strong>Credentials are protected</strong><p>Retrieve a short-lived client configuration through an authorized server operation. Passwords and private keys are never rendered in browser logs or status.</p></div></div></div></section><section class="detail-section"><div class="section-heading"><h3>Authentication</h3></div><dl class="info-grid"><div class="info-item"><dt>Transport</dt><dd>TLS</dd></div><div class="info-item"><dt>Mechanism</dt><dd>SCRAM-SHA-512</dd></div><div class="info-item"><dt>Kafka user</dt><dd><code>${escapeHtml(cluster.name)}-client</code></dd></div><div class="info-item"><dt>Access</dt><dd>Workspace scoped</dd></div></dl></section>`; }
  function logsHtml(cluster) { const result = state.observability.logs; if (result?.name === cluster.name && result.loading) return `<section class="detail-section"><div class="loading-state"><span>Loading broker logs…</span><span class="loading-bar" aria-hidden="true"></span></div></section>`; if (result?.name === cluster.name && result.error) return `<section class="detail-section"><div class="observability-box"><h3>Logs unavailable</h3><p>${escapeHtml(result.error)} Historical or live logs are an optional platform dependency and do not block Kafka operations.</p><button class="button button-secondary" type="button" data-action="load-logs">Retry logs</button></div></section>`; if (result?.name === cluster.name && result.data) return `<section class="detail-section"><div class="section-heading"><h3>Broker logs</h3><button class="button button-secondary" type="button" data-action="load-logs">Refresh</button></div><pre class="log-viewer" id="log-viewer">Loading…</pre></section>`; return `<section class="detail-section"><div class="observability-box"><h3>Live logs</h3><p>Logs are fetched through a fixed server-owned query scoped to <code>${escapeHtml(cluster.name)}</code>.</p><button class="button button-primary" type="button" data-action="load-logs">Load logs</button></div></section>`; }
  function metricsHtml(cluster) { const result = state.observability.metrics; if (result?.name === cluster.name && result.loading) return `<section class="detail-section"><div class="loading-state"><span>Loading broker metrics…</span><span class="loading-bar" aria-hidden="true"></span></div></section>`; if (result?.name === cluster.name && result.error) return `<section class="detail-section"><div class="observability-box"><h3>Metrics unavailable</h3><p>${escapeHtml(result.error)} VictoriaMetrics may be unavailable or not configured for this workspace.</p><button class="button button-secondary" type="button" data-action="load-metrics">Retry metrics</button></div></section>`; const metrics = result?.data || null; if (!metrics) return `<section class="detail-section"><div class="observability-box"><h3>Broker health</h3><p>Metrics use a fixed server-owned query. Namespace and cluster selectors are injected by the backend.</p><button class="button button-primary" type="button" data-action="load-metrics">Load metrics</button></div></section>`; const degradedNotice = result.degraded ? `<div class="observability-box" data-tone="warning"><h3>Metrics unavailable</h3><p>${escapeHtml(result.message || "The metrics provider is not configured; Kafka operations are unaffected.")}</p></div>` : ""; return `<section class="detail-section"><div class="section-heading"><h3>Broker health</h3><button class="button button-secondary" type="button" data-action="load-metrics">Refresh</button></div><div class="metric-grid">${[["Messages in", metrics.messagesIn ?? "—", "per second"], ["Messages out", metrics.messagesOut ?? "—", "per second"], ["Under-replicated", metrics.underReplicated ?? "—", "partitions"], ["Consumer lag", metrics.consumerLag ?? "—", "messages"]].map(([name, value, unit]) => `<div class="metric-card"><span>${name}</span><strong>${escapeHtml(value)}</strong><small>${unit}</small></div>`).join("")}</div>${degradedNotice}</section>`; }
  function render() { const clusters = filteredClusters(); renderNotice(); renderStats(clusters); renderClusterList(); renderDetail(); }

  async function loadClusters() { state.loading = true; setApiState("loading"); render(); try { const payload = await request(API_PREFIX); const items = Array.isArray(payload) ? payload : payload?.items || payload?.data || payload?.clusters || []; state.clusters = items; state.selected = state.selected || items[0]?.metadata?.name || items[0]?.name || null; setApiState("ready"); } catch (error) { if (error.code === 403) { state.clusters = []; state.selected = null; setApiState("forbidden", error.message); } else { state.clusters = DEMO_CLUSTERS; state.selected = state.selected || DEMO_CLUSTERS[0].metadata.name; setApiState("degraded", "The backend could not be reached. Demo data is read only; connect the API before creating resources."); } } finally { state.loading = false; render(); } }
  async function loadObservability(kind) { const cluster = selectedCluster(); if (!cluster) return; state.observability[kind] = { name: cluster.name, loading: true }; render(); try { const query = kind === "logs" ? "component=broker&tailLines=200" : "key=throughput"; const payload = await request(`${API_PREFIX}/${encodeURIComponent(cluster.name)}/${kind}?${query}`); if (kind === "logs") { const lines = Array.isArray(payload?.lines) ? payload.lines.map((line) => `${line.timestamp ? `[${line.timestamp}] ` : ""}${line.message}`).join("\n") : payload?.text || payload?.data || ""; state.observability[kind] = { name: cluster.name, data: lines, degraded: payload?.degraded, message: payload?.message }; } else { const values = Array.isArray(payload?.values) ? payload.values : []; const latest = values[values.length - 1]?.value; state.observability[kind] = { name: cluster.name, data: { messagesIn: latest ?? "—", messagesOut: "—", underReplicated: "—", consumerLag: "—" }, degraded: payload?.degraded, message: payload?.message }; } } catch (error) { state.observability[kind] = { name: cluster.name, error: error.code === 403 ? "You do not have permission to view this resource." : "The observability service did not respond." }; } render(); }
  async function createCluster(event) { if (event.submitter?.value === "cancel") return; event.preventDefault(); const form = event.currentTarget; const name = $("#cluster-name").value.trim(); const errorBox = $("#form-error"); if (!form.checkValidity()) { errorBox.hidden = false; errorBox.textContent = "Enter a valid cluster name and check the requested values."; form.reportValidity(); return; } state.createSubmitting = true; $("#submit-create").disabled = true; errorBox.hidden = true; try { await request(`${API_PREFIX}`, { method: "POST", body: JSON.stringify({ name, spec: { engine: "kafka", kafka: { version: $("#kafka-version").value, replicas: Number($("#broker-count").value) }, resources: { cpu: "1", memory: "2Gi" }, storage: { size: `${Number($("#storage-size").value)}Gi`, className: $("#storage-class").value.trim() || undefined }, deletionPolicy: $("#deletion-policy").value } }) }); $("#create-modal").close(); state.tab = "overview"; await loadClusters(); state.selected = name; render(); } catch (error) { errorBox.hidden = false; errorBox.textContent = error.code === 403 ? "Permission denied: your workspace cannot create clusters." : `Cluster creation failed: ${error.message}`; } finally { state.createSubmitting = false; $("#submit-create").disabled = false; } }
  function updateImpact() { const brokers = Number($("#broker-count").value || 1); const storage = Number($("#storage-size").value || 20); const deletion = $("#deletion-policy").value === "Delete" ? "Delete data with cluster" : "Retain data"; $("#impact-copy").textContent = `${brokers} broker${brokers === 1 ? "" : "s"} · ${storage} Gi storage · TLS and SCRAM authentication · ${deletion}`; }
  document.addEventListener("click", (event) => { const clusterButton = event.target.closest("[data-cluster]"); if (clusterButton) { state.selected = clusterButton.dataset.cluster; state.tab = "overview"; state.observability = {}; render(); return; } const tabButton = event.target.closest("[data-tab]"); if (tabButton) { state.tab = tabButton.dataset.tab; render(); return; } const action = event.target.closest("[data-action]")?.dataset.action; if (action === "open-create") { $("#create-modal").showModal(); $("#cluster-name").focus(); } if (action === "dismiss-notice") { $("#notice-region").innerHTML = ""; } if (action === "refresh-detail") loadClusters(); if (action === "load-logs") loadObservability("logs"); if (action === "load-metrics") loadObservability("metrics"); const copyButton = event.target.closest("[data-copy]"); if (copyButton) { navigator.clipboard?.writeText(copyButton.dataset.copy).then(() => { const original = copyButton.textContent; copyButton.textContent = "Copied"; setTimeout(() => { copyButton.textContent = original; }, 1400); }).catch(() => {}); } });
  $("#create-button").addEventListener("click", () => { $("#create-modal").showModal(); $("#cluster-name").focus(); });
  $("#create-form").addEventListener("submit", createCluster);
  ["#broker-count", "#storage-size", "#deletion-policy"].forEach((selector) => $(selector).addEventListener("input", updateImpact));
  $("#search-input").addEventListener("input", (event) => { state.search = event.target.value; render(); });
  $("#refresh-button").addEventListener("click", loadClusters);
  loadClusters();
})();
