{{- if .Values.podDisruptionBudget.controller.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "messagequeue.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "messagequeue.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.controller.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "messagequeue.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: controller
{{- end }}
{{- if .Values.podDisruptionBudget.backend.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "messagequeue.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "messagequeue.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.backend.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "messagequeue.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: backend
{{- end }}
{{- if .Values.podDisruptionBudget.frontend.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "messagequeue.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "messagequeue.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.frontend.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "messagequeue.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: frontend
{{- end }}
