apiVersion: v1
kind: Service
metadata:
  name: {{ include "messagequeue.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "messagequeue.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
    messagequeue.sealos.io/metrics: control-plane
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "messagequeue.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: controller
  ports:
    - name: metrics
      port: {{ .Values.controller.metrics.port }}
      targetPort: metrics
      protocol: TCP
    - name: health
      port: {{ .Values.controller.health.port }}
      targetPort: health
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "messagequeue.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "messagequeue.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "messagequeue.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: {{ .Values.backend.port }}
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "messagequeue.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "messagequeue.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "messagequeue.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.servicePort }}
      targetPort: http
      protocol: TCP
